version: "2"

services:
    hyperf-php:
        image: registry.cn-beijing.aliyuncs.com/jimmyci/hyperf-ip
        volumes:
            - .:/code
        command: php-fpm
        extra_hosts:
            - "ddmall-test.mengniu.cn:10.210.224.127"
        networks:
            - nai-network
    nai-think-worker:
        image: registry.cn-beijing.aliyuncs.com/all-channel/daojia-php-base
        volumes:
            - .:/code
            - ./nginx_conf/php.ini:/usr/local/etc/php/php.ini
        networks:
            - nai-network

    nai-think-worker-timer:
        image: registry.cn-beijing.aliyuncs.com/all-channel/daojia-php-base
        volumes:
            - .:/code
            - ./nginx_conf/php.ini:/usr/local/etc/php/php.ini
        working_dir: /code
        command: php think timer start
        networks:
            - nai-network

networks:
    nai-network:
        driver: bridge
